//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CFS_POS_Local_STD;Persist Security Info=True;User I" +
            "D=sa;Password=p@$$w0rd;")]
        public string CFS_POS_Local_STDConnectionString {
            get {
                return ((string)(this["CFS_POS_Local_STDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MYDOCUMENTS-PC\\SQLEXPRESS;Initial Catalog=Restaruant;Persist Security" +
            " Info=True;User ID=sa")]
        public string RestaruantConnectionString2 {
            get {
                return ((string)(this["RestaruantConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CFS_POS_Local;Persist Security Info=True;User ID=sa" +
            ";Password=p@$$w0rd")]
        public string RestaruantConnectionString {
            get {
                return ((string)(this["RestaruantConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CFS_POS_Local_FoodCourt;Persist Security Info=True;" +
            "User ID=sa;Password=p@$$w0rd")]
        public string CFS_POS_Local_FoodCourtConnectionString {
            get {
                return ((string)(this["CFS_POS_Local_FoodCourtConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CFS_POS_Local_WS;Persist Security Info=True;User ID" +
            "=sa;Password=p@$$w0rd")]
        public string CFS_POS_Local_WSConnectionString {
            get {
                return ((string)(this["CFS_POS_Local_WSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CFS_POS_LOCAL_WP;Persist Security Info=True;User ID" +
            "=sa;Password=p@$$w0rd")]
        public string CFS_POS_LocalConnectionString {
            get {
                return ((string)(this["CFS_POS_LocalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CFS_POS_Local_WP;Integrated Security=True")]
        public string CFS_POS_Local_WPConnectionString1 {
            get {
                return ((string)(this["CFS_POS_Local_WPConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CFS_POS_Local_SYS;Persist Security Info=True;User I" +
            "D=sa;Password=p@$$w0rd")]
        public string CFS_POS_Local_SYSConnectionString {
            get {
                return ((string)(this["CFS_POS_Local_SYSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CFS_POS_Local_TBC;Persist Security Info=True;User I" +
            "D=sa;Password=p@$$w0rd")]
        public string CFS_POS_Local_TBCConnectionString1 {
            get {
                return ((string)(this["CFS_POS_Local_TBCConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CFS_POS_LOCAL_TBC;Persist Security Info=True;User I" +
            "D=sa;Password=p@$$w0rd;")]
        public string CFS_POS_Local_TBCConnectionString {
            get {
                return ((string)(this["CFS_POS_Local_TBCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=thanvasucloud.com;Initial Catalog=CFS_CM_Infinity;Persist Security In" +
            "fo=True;User ID=uinet;Password=p@$$w0rd;")]
        public string CFS_POS_Local_BARConnectionString {
            get {
                return ((string)(this["CFS_POS_Local_BARConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.154.41.204;Initial Catalog=CFS_Thachang_S2;Persist Security Info=" +
            "True;User ID=uinet;Password=p@$$w0rd;")]
        public string CFS_POS_Local_WPConnectionString {
            get {
                return ((string)(this["CFS_POS_Local_WPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CFS_POS_Local_BAR;Persist Security Info=True;User I" +
            "D=sa")]
        public string CFS_POS_Local_BARConnectionString1 {
            get {
                return ((string)(this["CFS_POS_Local_BARConnectionString1"]));
            }
        }
    }
}
